name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: get short sha
      id: get_short_sha
      run: echo ::set-output name=VERSION::$(git rev-parse --short HEAD)
    
    - name: echo sha
      run: echo ${{ steps.get_short_sha.outputs.VERSION }}

    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.17

    # - name: Login to Docker
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ${{ secrets.DOCKER_REGISTRY }}
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build code
    #   run: make build
      
    # - name: Build image and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: ./
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_REGISTRY }}/willerdong/devops:${{ github.sha }}

    # - name: k8s deployment
    #   uses: steebchen/kubectl@v2
    #   with:
    #     version: 1.22
    #     config: ${{ secrets.KUBE_CONFIG }}
    #     command: apply -f ./deploy/k8s/deployment.yaml
    
    # - name: k8s service
    #   uses: steebchen/kubectl@v2
    #   with:
    #     version: 1.22
    #     config: ${{ secrets.KUBE_CONFIG }}
    #     command: apply -f ./deploy/k8s/service.yaml